# Dependencies

# Setup
title:            The Crypto Casebook
tagline:          'An open source case book on regulatory issues in cryptocurrency.'
description:      'An open source case book on regulatory issues in cryptocurrency.'
url:              https://sillsm.github.io/cryptoregs/
baseurl:          /

author:
  name:           'Max Sills'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sillsm/cryptoregs
