# Dependencies

# Setup
title:            The Crypto Casebook
tagline:          'An open source case book on regulatory issues in cryptocurrency.'
description:      'An open source case book on regulatory issues in cryptocurrency.'
url:              https://sillsm.github.io/cryptoregs/
baseurl:          /

author:
  name:           'Max Sills'

collections_dir: chapters
collections:
  pizza:
    output: true
  chapter2_sec_howey:
    output: true
  
paginate:         5

# --- List of links in the navigation bar --- #

navbar-links:
  Chapter 1 The Regulatory Loop: "chapters/Chapter1_The_Regulatory_Loop"
  Chapter 2 SEC: "chapters/howey"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sillsm/cryptoregs
