# Dependencies

# Setup
title:            The Crypto Casebook
tagline:          'An open source case book on regulatory issues in cryptocurrency.'
description:      'An open source case book on regulatory issues in cryptocurrency.'
url:              https://sillsm.github.io/cryptoregs/
baseurl:          /

author:
  name:           'Max Sills'

collections_dir: chapters
collections:
  chapter1intro:
    title: "Chapter 1 Introduction"
    output: true
  chapter2sec:
    output: true
    title: "Chapter 2 SEC"
  chapter3cftc:
    output: true
    title: "Chapter 3 CFTC"
  chapter4irs:
    output: true
    title: "Chapter 4 IRS"
  
paginate:         5

# --- List of links in the navigation bar --- #

navbar-links:
  Chapter 1 The Regulatory Loop: "chapters/Chapter1_The_Regulatory_Loop"
  Chapter 2 SEC: "chapter2_sec_howey/001_intro"
  Chapter 4 IRS: "chapter4_IRS/001_intro"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sillsm/cryptoregs
